name: awesome-lint
on:
  pull_request:
    branches: [main]
jobs:
  # Run awesome linter
  # https://github.com/sindresorhus/awesome-lint
  awesome_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npx awesome-lint